### ISSUE TITLE
JSON output starttime and endtime secs need to be numeric, not strings

### ISSUE THREAD

**Issue by mgoldey** [finos/greenkey-asrtoolkit#77]
**Is your feature request related to a problem? Please describe.**
GK JSON schema has been better defined since asrtoolkit first output to it.

**Describe the solution you'd like**
They should be floats

**Describe alternatives you've considered**
We could maintain both or switch to strings

**Additional context**
GK schema last edited by @burrows

**Comment by mgoldey** [comment]
heads up @cbrochtrup

**Comment by cbrochtrup** [comment]
Fixed in #78
