### ISSUE TITLE
wer rate is 400%

### ISSUE THREAD

**Issue by entheos37** [finos/greenkey-asrtoolkit#80]
Hi I use `Python 3.5.3 :: Anaconda custom (x86_64)` and when I ran the command `wer answer.txt stt.txt` the result was wer 400%

![스크린샷 2019-12-05 오후 5 52 23](https://user-images.githubusercontent.com/16621093/70219345-04199d00-1788-11ea-8b98-2f69e8a6bdb1.png)

My another coworker tried this with same files, same comand, the python version was `3.6.8` but he got the result seemed normal like wer 49.485 % . His computer is Ubuntu and I use Mac OS

Other coworkers (One Ubuntu, one Windows) also tried and they got the wer 400% result like me so can you help me to figure out the reason that the calculation result is different from me and the other person even though using same files and same command?

Thank you!!!

**Comment by entheos37** [comment]
I share the sample files. The wer result was 0.00 % for me but my coworker result was WER: 100.000%, CER: 33.333% >> seems good!! not like my result for same files, same command `wer answer.txt stt.txt`
[answer.txt](https://github.com/finos/greenkey-asrtoolkit/files/3925915/answer.txt)
[stt.txt](https://github.com/finos/greenkey-asrtoolkit/files/3925916/stt.txt)

**Comment by tshastry** [comment]
@entheos37 thank you for raising this issue. Do you have any information on whether you observe this across versions on a machine? (i.e. does it work on 3.6.8 on Mac OS or does it fail on 3.5.3 on Ubuntu)?

**Comment by entheos37** [comment]
Hi @tshastry  Thank you for reaching me out. 

1. Working Case
- 3.6.8 Python & Ubuntu 
2. Failed Cases
- 3.7.x Python on Windows 10 
- 3.5.3 Python on Mac OS. 
- I don't know the failed case of the version of Python on Ubuntu.

But three failed cases recently installed the library but the only successful one installed previously.

**Comment by mgoldey** [comment]
Hi @entheos37 , please feel free to test asrtoolkit release 0.2.0 (available on [pypi](https://pypi.org/project/asrtoolkit/)) and confirm that this works in your environment. The package can be upgraded using `python3 -m pip install -u asrtoolkit`.

**Comment by entheos37** [comment]
Hi @mgoldey recently I test this and I find it works now. Thank you very much :)
