### ISSUE TITLE
Potential typo in align_json.py

### ISSUE THREAD

**Issue by kaleko** [finos/greenkey-asrtoolkit#94]
**Describe the bug**
Line 58 of align_json.py: https://github.com/finos/greenkey-asrtoolkit/blob/master/asrtoolkit/align_json.py

Should this be "`align_json(`", not "`align_gk_json(`"? I don't see `align_gk_json` anywhere else in the repo.

**To Reproduce**
3. Execute '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python version
 - Using docker or pip package?

**Additional context**

**Comment by mgoldey** [comment]
Thanks a bunch for catching this. Potential fix up and will re-evaluate testing procedure.
